--- 
- name: Configure db hosts
  hosts: db
  become: true
  tags: db-tag
  vars:
    mongo_bind_ip: 0.0.0.0
  tasks:
    - name: Change mongo config file
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      notify: restart mongod

  handlers:
  - name: restart mongod
    service: name=mongod state=restarted 

- name: Configure app hosts
  hosts: app
  become: true
  tags: app-tag 
  vars:
    db_host: 10.128.0.50 
 
  tasks:
    - name: Add unit file for Puma       
      copy:        
        src: files/puma.service  
        dest: /etc/systemd/system/puma.service        
      notify: reload puma
      
    - name: enable puma   
      systemd: name=puma enabled=yes

    - name: Add config for DB connection      
      template:        
        src: templates/db_conÔ¨Åg.j2        
        dest: /home/appuser/db_config  
        owner: appuser
        group: appuser    

  handlers:
  - name: reload puma   
    systemd: name=puma state=reloaded



